# 工作流的名称
name: Navix Auto Comment Bot

on:
  # 1. 定时触发
  schedule:
    # 【重要修改】cron 表达式使用 UTC 时间。
    # 北京时间 (UTC+8) 的 01:00 AM，对应 UTC 时间是前一天的 17:00 (下午5点)。
    - cron: '0 17 * * *'
  
  # 2. 手动触发
  workflow_dispatch:

jobs:
  run-comment-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run comment script
        env:
          # 第一个账号
          NAVIX_EMAIL: ${{ secrets.NAVIX_EMAIL }}
          NAVIX_PASSWORD: ${{ secrets.NAVIX_PASSWORD }}
          
          # 第二个账号 (如果需要启用，请取消下面的注释)
          # NAVIX_EMAIL2: ${{ secrets.NAVIX_EMAIL2 }}
          # NAVIX_PASSWORD2: ${{ secrets.NAVIX_PASSWORD2 }}
          
          # 【新增】为邮件功能提供 Secrets
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}

        run: python comment_bot.py
